#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define LITERATA_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./literata_12_regular.h",
  "./literata_12_bold.h",
  "./literata_12_bolditalic.h",
  "./literata_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define LITERATA_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./literata_14_regular.h",
  "./literata_14_bold.h",
  "./literata_14_bolditalic.h",
  "./literata_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define LITERATA_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./literata_16_regular.h",
  "./literata_16_bold.h",
  "./literata_16_bolditalic.h",
  "./literata_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define LITERATA_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./literata_18_regular.h",
  "./literata_18_bold.h",
  "./literata_18_bolditalic.h",
  "./literata_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BEVIETNAM_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bevietnam_12_regular.h",
  "./bevietnam_12_bold.h",
  "./bevietnam_12_bolditalic.h",
  "./bevietnam_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BEVIETNAM_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bevietnam_14_regular.h",
  "./bevietnam_14_bold.h",
  "./bevietnam_14_bolditalic.h",
  "./bevietnam_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BEVIETNAM_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bevietnam_16_regular.h",
  "./bevietnam_16_bold.h",
  "./bevietnam_16_bolditalic.h",
  "./bevietnam_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BEVIETNAM_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bevietnam_18_regular.h",
  "./bevietnam_18_bold.h",
  "./bevietnam_18_bolditalic.h",
  "./bevietnam_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define VOLLKORN_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./vollkorn_12_regular.h",
  "./vollkorn_12_bold.h",
  "./vollkorn_12_bolditalic.h",
  "./vollkorn_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define VOLLKORN_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./vollkorn_14_regular.h",
  "./vollkorn_14_bold.h",
  "./vollkorn_14_bolditalic.h",
  "./vollkorn_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define VOLLKORN_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./vollkorn_16_regular.h",
  "./vollkorn_16_bold.h",
  "./vollkorn_16_bolditalic.h",
  "./vollkorn_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define VOLLKORN_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./vollkorn_18_regular.h",
  "./vollkorn_18_bold.h",
  "./vollkorn_18_bolditalic.h",
  "./vollkorn_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_10_regular.h",
  "./ubuntu_10_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_12_regular.h",
  "./ubuntu_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"
