#pragma once

#include <builtinFonts/bevietnam_ui_8_regular.h>
// Vietnamese fonts - Literata
#include <builtinFonts/literata_12_bold.h>
#include <builtinFonts/literata_12_bolditalic.h>
#include <builtinFonts/literata_12_italic.h>
#include <builtinFonts/literata_12_regular.h>
#include <builtinFonts/literata_14_bold.h>
#include <builtinFonts/literata_14_bolditalic.h>
#include <builtinFonts/literata_14_italic.h>
#include <builtinFonts/literata_14_regular.h>
#include <builtinFonts/literata_16_bold.h>
#include <builtinFonts/literata_16_bolditalic.h>
#include <builtinFonts/literata_16_italic.h>
#include <builtinFonts/literata_16_regular.h>
#include <builtinFonts/literata_18_bold.h>
#include <builtinFonts/literata_18_bolditalic.h>
#include <builtinFonts/literata_18_italic.h>
#include <builtinFonts/literata_18_regular.h>
// Vietnamese fonts - Be Vietnam Pro
#include <builtinFonts/bevietnam_12_bold.h>
#include <builtinFonts/bevietnam_12_bolditalic.h>
#include <builtinFonts/bevietnam_12_italic.h>
#include <builtinFonts/bevietnam_12_regular.h>
#include <builtinFonts/bevietnam_14_bold.h>
#include <builtinFonts/bevietnam_14_bolditalic.h>
#include <builtinFonts/bevietnam_14_italic.h>
#include <builtinFonts/bevietnam_14_regular.h>
#include <builtinFonts/bevietnam_16_bold.h>
#include <builtinFonts/bevietnam_16_bolditalic.h>
#include <builtinFonts/bevietnam_16_italic.h>
#include <builtinFonts/bevietnam_16_regular.h>
#include <builtinFonts/bevietnam_18_bold.h>
#include <builtinFonts/bevietnam_18_bolditalic.h>
#include <builtinFonts/bevietnam_18_italic.h>
#include <builtinFonts/bevietnam_18_regular.h>
// Vietnamese fonts - Vollkorn
#include <builtinFonts/vollkorn_12_bold.h>
#include <builtinFonts/vollkorn_12_bolditalic.h>
#include <builtinFonts/vollkorn_12_italic.h>
#include <builtinFonts/vollkorn_12_regular.h>
#include <builtinFonts/vollkorn_14_bold.h>
#include <builtinFonts/vollkorn_14_bolditalic.h>
#include <builtinFonts/vollkorn_14_italic.h>
#include <builtinFonts/vollkorn_14_regular.h>
#include <builtinFonts/vollkorn_16_bold.h>
#include <builtinFonts/vollkorn_16_bolditalic.h>
#include <builtinFonts/vollkorn_16_italic.h>
#include <builtinFonts/vollkorn_16_regular.h>
#include <builtinFonts/vollkorn_18_bold.h>
#include <builtinFonts/vollkorn_18_bolditalic.h>
#include <builtinFonts/vollkorn_18_italic.h>
#include <builtinFonts/vollkorn_18_regular.h>
// UI fonts (Be Vietnam Pro - supports Vietnamese)
#include <builtinFonts/bevietnam_ui_10_bold.h>
#include <builtinFonts/bevietnam_ui_10_regular.h>
#include <builtinFonts/bevietnam_ui_12_bold.h>
#include <builtinFonts/bevietnam_ui_12_regular.h>
